version: "3"
services:
  db:
    image: mongo
    restart: always
    container_name: "emourge_db"
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - emourge:/data/db

  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    container_name: "emourge_bot"
    depends_on:
      - db

volumes:
  emourge:
